const data = [
    {
        img: './src/imgs/Jacket.png',
        tag: 'Camisetas',
        titulo: 'Jaqueta preta',
        descricao: 'Adicione um pouco de energia ao seu guarda-roupa de inverno com esta jaqueta vibrante...',
        preco: 'R$ 100.00',
        addCarrinho: 'Adicionar ao carrinho',
    },
    {
        img: './src/imgs/blackhat.png',
        tag: 'Acessórios',
        titulo: 'Toca preta',
        descricao: 'O gorro Next.js chegou! Esta beldade bordada tem um ajuste confortável que garante que...',
        preco: 'R$ 100.00',
        addCarrinho: 'Adicionar ao carrinho',
    },
    {
        img: './src/imgs/Mask.png',
        tag: 'Acessórios',
        titulo: 'Máscara',
        descricao: 'Esta máscara facial durável é feita de duas camadas de tecido tratado e possui presilhas...',
        preco: 'R$ 40.00',
        addCarrinho: 'Adicionar ao carrinho',
    },
    {
        img: './src/imgs/TShirt-Black.png',
        tag: 'Camisetas',
        titulo: 'Camiseta preta',
        descricao: 'Esta t-shirt é imprescindível no seu guarda-roupa, combinando o caimento intemporal de...',
        preco: 'R$ 100.00',
        addCarrinho: 'Adicionar ao carrinho',
    },
    {
        img: './src/imgs/TShirt-White.png',
        tag: 'Camisetas',
        titulo: 'Camiseta branca',
        descricao: 'Agora você encontrou a camiseta básica do seu guarda-roupa. É feito de um mais grosso...',
        preco: 'R$ 100.00',
        addCarrinho: 'Adicionar ao carrinho',
    },
    {
        img: './src/imgs/mockup.png',
        tag: 'Camisetas',
        titulo: 'Jaqueta embalável',
        descricao: 'Proteja-se dos elementos com esta jaqueta embalável Champion. Esta jaqueta de poliést...',
        preco: 'R$ 100.00',
        addCarrinho: 'Adicionar ao carrinho',
    },  
]